### ISSUE TITLE
TypeError: Cannot assign to read only property 'warnings' of true

### ISSUE THREAD

**Issue by rauberdaniel** [gruntjs/grunt-contrib-uglify#298] opened 2015-02-12 21:38 UTC
I recently updated to node 0.12.0 and right now I’m getting the following error with grunt-contrib-uglify version 0.7.0:

```
Running "uglify:min" (uglify) task
[TypeError: Cannot assign to read only property 'warnings' of true]
>> Uglifying source static/js/main.js failed.
Warning: Uglification failed.
Cannot assign to read only property 'warnings' of true.
 Use --force to continue.

Aborted due to warnings.
```

Happens with any .js file, so it seems to be a bug either with nodejs v0.12.0 or with this uglify task. Any ideas?

**Comment by rauberdaniel** [comment] 2015-02-12 21:55
I guess I found the reason: Having set the option `compress` to `true` instead of `{}` (which is allowed by documentation) causes the issue.

**Comment by pyalxx** [comment] 2015-02-13 14:41
+1! You saved my day, thanks!

**Comment by XhmikosR** [comment] 2015-02-18 13:04
Duplicate of #287.

**Closed by XhmikosR** 2015-02-18 13:04 UTC

**Comment by NorikDavtian** [comment] 2015-03-26 02:49
:+1: @rauberdaniel tnxx

**Comment by ahmednuaman** [comment] 2015-04-08 07:46
So I had this problem too, but it was fixed by running `git clean -xdf` and `npm install` again.

**Comment by 4aficiona2** [comment] 2015-08-07 15:41
replacing `true` with `{}` worked for me too. Thanks @rauberdaniel

**Comment by 2013gang** [comment] 2015-08-14 16:55
+1

**Comment by willthemoor** [comment] 2015-08-28 15:50
Thank you @rauberdaniel!

**Comment by Deanzie** [comment] 2015-09-04 19:19
+1

**Comment by amccarthyMatchbook** [comment] 2017-07-25 13:52
+1
