### ISSUE TITLE
Undocumented beautify.comments property can cause unexpected behaviour.

### ISSUE THREAD

**Issue by SmartArtsStudio** [gruntjs/grunt-contrib-uglify#384] opened 2016-01-17 04:51 UTC
http://lisperator.net/uglifyjs/codegen documents the following property:

"beautify.comments      : false, // output comments?"
...is not documented on GitHub Uglify/UglifyJS2 or grunt-contrib-uglify but still unofficially supported?

When providing a custom comments function to options.preserveComments.
When customising the beautify output:
beautify.comments = true;  // overrides custom comment function and prints out all comments.
beautify.comments = false;   // overrides custom comment function and prints out no comments.
NOT defining beautify.comments = value //  custom comment function prevails!

Is that a result of grunt-contrib-uglify internally not having a default for it because it is unclear whether it is still officially supported? 
beautify.comments = undefined 

I was not expecting "not defining beautify.comments with a value" to give me anything different to the behavior of either true or false. Thankfully it does.

If this was not the intended behavior I just thought I would mention it to make sure it is not changed, if it is raised in the future.

**Comment by avdg** [comment] 2016-01-17 12:58
Uh, I think you need a better code example. Please give some code that shows the option and how its used.

**Comment by SmartArtsStudio** [comment] 2016-01-17 23:47
```
grunt.config.init( {

    uglify: {
        // strip all comments but custom /*# comments*/
        stripComments: {
            options: {
                mangle          : false,
                compress        : false,
                preserveComments: function ( node, comment ) {
                    // keeps /*# comments*/
                    return comment.type == 'comment2' && comment.value.charAt( 0 ) == '#';
                },
                beautify        : {
                    beautify     : true,
                    indent_level : 4,
                    indent_start : 0,
                    quote_keys   : false,
                    space_colon  : true,
                    ascii_only   : false,
                    inline_script: false,
                    width        : 80,
                    max_line_len : 32000,
                    source_map   : null,
                    bracketize   : true,
                    semicolons   : true,
                    preamble     : null,
                    quote_style  : 0,
                    // documented here http://lisperator.net/uglifyjs/codegen 
                    // but not documented on GitHub Uglify/UglifyJS2 or grunt-contrib-uglify. 
                    comments     : true,    // task keeps ALL comments. (preserveComments function overridden? ignored? sucessful? )
                    comments     : false,   // task keeps NO comments.  (preserveComments function overridden or ignored! )
                 // comments  : undefined   // Don't even mention comment in object definition:
                                            // preserveComments function prevails and task
                                            // keeps all /*# comments*/ stripping all others ('yay')
                }
            },
            files  : [
                {/* file details*/}
            ]
        }
    }
});
```
I assumed not defining 'comments' would default to either true's or false's behaviour accordingly. To my surprise it  resulted in a third behavior... which is a good thing!

I assume it is depreciated. Just thought I would mention it in case its messing with someone else's, custom preserveComments. And vote to keep this current behaviour.

**Comment by avdg** [comment] 2016-01-18 10:45
true and false behaviour is still supported on the uglifyjs side. also "all" is supported which is a sort of alias of true. I did refactored the comments handling and did attempt to keep all options in as it was before, but due to a lack of tests and lack of knowledge of these features they might not have been kept.

At least, I don't know what's happened, I will take a look (on the mishoo/uglifyjs2 repo) and will throw a lot on tests on it to make sure these kind of situations will never happen in the future.

**Comment by avdg** [comment] 2016-01-18 11:05
For comments, there is still an option to support strings as predefined sets (except for the option "all", "true" or "false" through commandline). But for now its not supported because of a few reasons:

1. There is no support on the uglifyjs side to store configurations (being .uglifyjs, npm settings, or presets clearly defined by standards/organizations/specialized index sites)
1. There is no db to store some sets, or any clear organization or standard to define comment filters

**Comment by avdg** [comment] 2016-01-18 11:06
For grunt-contrib-uglify options, I might need to inventorize the options before I can align them better though.

**Comment by avdg** [comment] 2016-01-19 15:15
beautify options are just send straight to uglify's output option (see https://github.com/gruntjs/grunt-contrib-uglify/blob/ea77dde2ac86d507f37f6a06c88ed2afbc007c06/tasks/lib/uglify.js#L209).

The preserveComments is defined later in the code (see https://github.com/gruntjs/grunt-contrib-uglify/blob/ea77dde2ac86d507f37f6a06c88ed2afbc007c06/tasks/lib/uglify.js#L262).

Since both are assigning to the same objects, the latter option will always win in cases where both are set. Since I'm just contributing where I'm aware there are problems and didn't really write the code, I have to ask myself if this is intended and how this should be solved myself :-)

At least I hope you know why this is the case now :-)

**Comment by SmartArtsStudio** [comment] 2016-01-19 22:07
Thanks for the insight, it may actually be the intended result. Because without it, if the 'comment' option had a 'strict' Boolean behaviour, in my use case my custom preserveComments would not have the opportunity to succeed. 

It may just help others save some head scratching if its documented that the 'comment' boolean value will override a custom preserveComments function (and anything else in preserveComments that it may or may not override, if it overrides other stuff aswell.) 

It would probably rarely come up since it is a potentially depreciated option being that it is only documented at http://lisperator.net/uglifyjs/codegen. I just happens to stumble across it trying to do get uglify to NOT do 95% of what uglify is designed to do. Thought I would mention it in case the developers were not even aware of it, to think to clarify it.

Thanks again for your insight.

**Comment by avdg** [comment] 2016-01-19 22:15
Hmm... I'm not sure I can fix these issues as I'm already quite busy

**Comment by XhmikosR** [comment] 2016-07-13 19:32
@SmartArtsStudio; I believe the issue is https://github.com/gruntjs/grunt-contrib-uglify/commit/fca1a067f0f81ccfd636dfa524e1b3b7bdcb7467

**Comment by XhmikosR** [comment] 2017-03-30 21:35
This should work fine with the latest version; if not please provide a full test case.

**Closed by XhmikosR** 2017-03-30 21:35 UTC
