### ISSUE TITLE
file code order

### ISSUE THREAD

**Issue by landsman** [gruntjs/grunt-contrib-uglify#434] opened 2016-08-28 23:46 UTC
Hi,

how can i setup code order observance? For example i have variable after functions in uglify file but in original are at top ...

Thanks

**Comment by UltCombo** [comment] 2016-08-28 23:52
Looks like a dupe of #381

**Comment by XhmikosR** [comment] 2017-03-30 21:36
https://github.com/gruntjs/grunt-contrib-uglify/issues/271

**Closed by XhmikosR** 2017-03-30 21:36 UTC
