### ISSUE TITLE
uglifyjs error

### ISSUE THREAD

**Issue by Simple2012hcz** [gruntjs/grunt-contrib-uglify#420] opened 2016-07-15 09:27 UTC
we use grunt-contrib-uglifyjs angularjs with default or mangle = false ,in android 2.3 os run error.
but uglifyjs2 uglify ,with option -m -o ,can run ok in android 2.3 .

**Comment by avdg** [comment] 2016-07-15 12:14
Any idea how the error looks like? We like to be pinpointed to the cause of the error. Thanks

**Comment by XhmikosR** [comment] 2017-03-30 21:33
Lack of info and probably an upstream issue, so closing.

**Closed by XhmikosR** 2017-03-30 21:33 UTC
