### ISSUE TITLE
Multiple files uglify did not work

### ISSUE THREAD

**Issue by TeodorKolev** [gruntjs/grunt-contrib-uglify#365] opened 2015-10-31 18:02 UTC
That doesn't work
```javascript
 uglify: {
            build: {
                files: [{
                    expand: true,
                    src: '**/*.js',
                    dest: 'dist/js',
                    cwd: 'src/js'
                }]
            }
        }
```

**Comment by johnjspiteri** [comment] 2015-12-16 21:13
@TeodorKolev, wondering... have you tried manually setting the file order to rule out "if" any of the files in your directories are causing the error?

```javascript
    target: {
        files: {
            'client/js/app.min.js': [
                'client/js/app/app.module.js'
           
```

**Comment by XhmikosR** [comment] 2016-07-19 07:02
Closing since the info we have is not enough.

Feel free to provide a test repo to reproduce the problem.

**Closed by XhmikosR** 2016-07-19 07:02 UTC
