### ISSUE TITLE
Stripping comments regardless of the preserveComments setting

### ISSUE THREAD

**Issue by IanCaunce** [gruntjs/grunt-contrib-uglify#279] opened 2014-12-03 20:01 UTC
Regardless of the preserveComments setting if the comment is followed by a semi colon, it will be stripped during the minification process. 

Example:
/*! Comment */
;(function($){

})(jQuery)

**Comment by XhmikosR** [comment] 2015-02-17 11:57
Duplicate of #273

**Closed by XhmikosR** 2015-02-17 11:57 UTC
