### ISSUE TITLE
files with . in the filename are renamed incorrectly. 

### ISSUE THREAD

**Issue by helgatheviking** [gruntjs/grunt-contrib-uglify#383] opened 2016-01-15 20:16 UTC
Files such as `jquery.livesearch.js` are being renamed to `jquery.min.js` when minified. 

If it helps, here's my gruntfile config for uglify:

```
	uglify: {
		options: {
			compress: {
				global_defs: {
					"EO_SCRIPT_DEBUG": false
				},
				dead_code: true
				},
			banner: '/*! <%= pkg.title %> <%= pkg.version %> <%= grunt.template.today("yyyy-mm-dd HH:MM") %> */\n'
		},
		build: {
			files: [{
				expand: true,	// Enable dynamic expansion.
				cwd: 'assets/js',
				dest: 'assets/js',
				src: [ '**/*.js'], // Actual pattern(s) to match.
				ext: '.min.js',   // Dest filepaths will have this extension.
			}]
		}
	},
```

**Comment by avdg** [comment] 2016-01-16 22:41
Can reproduce, see https://gist.github.com/avdg/4226e11ddd761cdfa6ff for reproduction

**Comment by UltCombo** [comment] 2016-01-16 22:49
Try `extDot: 'last'`
http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically

**Comment by avdg** [comment] 2016-01-16 23:06
That would also select the .min.js files though

**Comment by avdg** [comment] 2016-01-16 23:06
Solution would be to change the dest directory

**Comment by UltCombo** [comment] 2016-01-16 23:57
How about `exDot: 'last', src: ['**/*.js', '!'**/*.min.js'']`

**Comment by UltCombo** [comment] 2016-01-16 23:59
Update: fixed a typo in the code sample above.

**Comment by avdg** [comment] 2016-01-17 00:01
whatever works I guess :-) (and ty for sharing)

**Comment by UltCombo** [comment] 2016-01-17 00:06
No problem. :smiley:
I also agree that a different dest directory would be a better option, I prefer to avoid using negated globs needlessly. Changing the directory may or may not be viable for the user, so we can leave both possible solutions.

**Comment by helgatheviking** [comment] 2016-01-19 00:30
I can confirm that @UltCombo's suggestion works for me.

**Comment by XhmikosR** [comment] 2016-08-15 12:01
Closing since this is by design.  http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically

**Closed by XhmikosR** 2016-08-15 12:01 UTC
