### ISSUE TITLE
regression in reporter

### ISSUE THREAD

**Issue by naugtur** [gruntjs/grunt-contrib-uglify#276] opened 2014-11-18 17:58 UTC
What is the point of setting `report` option if the result is only visible in verbose mode? 
Wouldn't it make more sense to log the minification report if `report` was set to any value, and skip counting entirely if it's not set?

**Comment by XhmikosR** [comment] 2015-02-17 11:54
Duplicate of #254

**Closed by XhmikosR** 2015-02-17 11:54 UTC
