### ISSUE TITLE
`preserveComments:some` option is broken

### ISSUE THREAD

**Issue by skfd** [gruntjs/grunt-contrib-uglify#426] opened 2016-07-29 16:20 UTC
[Recent commit](https://github.com/gruntjs/grunt-contrib-uglify/pull/338/files) broke the `preserveCommentss:some` option. It just passes text down to Uglify now.

Is `some` option dropped by design?

**Comment by avdg** [comment] 2016-07-29 21:58
Just passing `/^!|@preserve|@license|@cc_on/i` should work fine though. I don't know what happens there, but maybe this should be fixed upstream if an agreement can be gained there.

**Comment by skfd** [comment] 2016-07-29 23:32
Uplift had no native some option as far as I understood.

**Comment by avdg** [comment] 2016-07-29 23:33
only using the cli interface

**Comment by skfd** [comment] 2016-08-01 10:48
@avdg I did just that, but that's a clear regression that could cause production issues -- see https://github.com/moment/moment/issues/3283 for example.

**Comment by avdg** [comment] 2016-08-01 10:55
It's still weird that someone makes a suggestion, the patch get merged without question and getting complains afterwards :/

The patch was intended to break stuff.

**Comment by XhmikosR** [comment] 2016-08-14 06:07
This is by design as far as I can tell.

/CC @vladikoff

**Comment by avdg** [comment] 2016-08-15 00:24
Please send patches upstream on uglify, it's the best way to close this discussion.

**Comment by XhmikosR** [comment] 2016-08-15 00:26
@avdg: true but this issue is for our removed option, not upstream.

**Comment by avdg** [comment] 2016-08-15 00:46
Ok I get it... we should be 100% annoying by design without getting users agreement. I better give this stuff up for now :/

**Comment by skfd** [comment] 2016-08-15 11:16
Changelog does not say anything about this breaking change. It's ok to break thing, but it should be in the change log.

**Comment by XhmikosR** [comment] 2016-08-15 11:37
Either way, closing this for now. There is a known solution to get the same behavior plus you should ask for this upstream.

**Closed by XhmikosR** 2016-08-15 11:37 UTC

**Comment by cheshrkat** [comment] 2016-08-15 12:08
If I'm reading this thread correctly (and I may not be) grunt-contrib-uglify has effectively removed the `some` option? If so it should be removed from the docs..?

**Comment by XhmikosR** [comment] 2016-08-15 12:15
Feel free to make a PR for that.

**Comment by cheshrkat** [comment] 2016-08-15 12:52
I'll take that as confirmation the option was removed.

**Comment by skfd** [comment] 2016-08-15 13:35
I think you should not remove it docs about `some`. You should document that this option was removed and warn if someone tries to use it as a parameter.

**Comment by cheshrkat** [comment] 2016-08-15 15:21
My PR just removes documentation of a feature that doesn't exist or work. I think there are deeper issues with the API...

The upstream API includes `--comments` (https://github.com/mishoo/UglifyJS2) which works the way `some` is documented. That is, it preserves comments with explicit preserve flags.

Based on my testing, the grunt-contrib-uglify plugin doesn't reproduce that with any configuration of `preserveComments`; it either strips everything or keeps everything, but no combination kept the preserved comments. Happy to be corrected if I've missed something here, I've just read the docs and not dug through the codebase (I was just trying to use contrib uglify in a project :)).

My test cases were:

    /*! Preserved comment */
    /* @preserve preserved comment */
    /* @preserve preserved comment
     * 
     */
    /* @license preserved comment
     * 
     */
    /* @cc_on preserved comment */
    // Unpreserved comment

What I think should happen _assuming the intent is to mirror Uglify2_:

- `preserveComments:true` should preserve comments explicitly marked for preservation but strip all others.
- `preserveComments:all` should keep all comments.
- `preserveComments:false` should strip all comments.

Removing `some` makes sense, as it's not in the upstream API either (hence my PR). It just seems that the behaviour of `true` is wrong.

Happy to push this over to a new issue people actually agree, but I really don't know what the maintainers have in mind for this feature?

**Comment by XhmikosR** [comment] 2016-08-15 16:01
You are missing the point. `preserveCOmments` just passes its value to uglify's `comments` option.

```js
if (typeof options.preserveComments !== 'undefined') {
  outputOptions.comments = options.preserveComments;
}
```

**Comment by skfd** [comment] 2016-08-15 16:15
Yes, but check out [how many people](https://github.com/search?q=preserveComments%3A+%27some%27&type=Code&utf8=%E2%9C%93) use `some` option that was quietly removed. You're giving them no warning. All their minified resources would have comments in them. Come on, just give this option back.

**Comment by XhmikosR** [comment] 2016-08-15 16:17
It was not my choice to merge it. I would still remove it though.

**Comment by cheshrkat** [comment] 2016-08-16 07:59
This thread is hung up on the wrong point, I've raised https://github.com/gruntjs/grunt-contrib-uglify/issues/430 with details and tests to illustrate what I think is the problem.

**Comment by avdg** [comment] 2016-10-23 21:52
Api has been changed on 2.7.4 to include accepting `some` and stringified regexes as valid options for the comment filter.

**Comment by XhmikosR** [comment] 2016-10-25 18:52
Feel free to update the docs and CC me.
