### ISSUE TITLE
Support for ECMA script 6

### ISSUE THREAD

**Issue by mkappelhof** [gruntjs/grunt-contrib-uglify#482] opened 2017-07-04 10:17 UTC
When compiling my code with ECMA script 6 class definitions `class ClassName{ [code] }` i get the following:

> Warning: Uglification failed.
> Unexpected token: name (ClassName).
> Line 1 in script.js

I've read your comment here [here](https://github.com/gruntjs/grunt-contrib-uglify/issues/279#issuecomment-65479239), so is it an option (don't really know how these things work) to add [uglify-js-es6](https://www.npmjs.com/package/uglify-js-es6) to this wrapper?

**Comment by alexlamsl** [comment] 2017-07-04 12:03
Closing as duplicate of #480 - please use `harmony` branch for ES6 support, which depends on `uglify-es`.

**Closed by alexlamsl** 2017-07-04 12:03 UTC

**Comment by mkappelhof** [comment] 2017-07-05 13:36
Works perfect! Thx

**Comment by FromStoneage** [comment] 2017-12-27 21:55
can we get this change to master? for those that rely on ES6 support every time the master branch updates the harmony's rebase caused shrinkwrap unable to find the dependency and we have to fix the build.

What's preventing this feature to be merged to master?

**Comment by jakubboucek** [comment] 2019-09-25 19:01
- [Package `grunt-contrib-uglify-es`](https://www.npmjs.com/package/grunt-contrib-uglify-es) is now **deprecated**,  
- [Branch `#harmony`](https://github.com/gruntjs/grunt-contrib-uglify/tree/harmony) is more than 2 years old,  
- [Current version of this plugin](https://github.com/gruntjs/grunt-contrib-uglify/releases/tag/v4.0.1) is using `uglify-js` v3.5.0 which is still support only ES5. 

Is here any stable & non-deprecated way to uglify ES6 now?

**Comment by nise** [comment] 2019-11-29 12:00
Are there any updates?

**Comment by ImLoaD** [comment] 2020-09-29 12:36
Branch #harmony is more than 3 years old,
Any updates?

**Comment by ShakMR** [comment] 2021-06-04 15:11
> Branch #harmony is more than 3 years old,
> Any updates?

just in case someone finds this issue first, it is deprecated and we should be using terser instead. See: 
https://github.com/gruntjs/grunt-contrib-uglify/issues/541

**Comment by alexlamsl** [comment] 2021-06-04 15:41
Incorrect &minus; current version of `uglify-js` supports latest version of ECMAScript, so using `grunt-contrib-uglify` without the harmony branch is sufficient.

**Comment by ShakMR** [comment] 2021-06-07 09:27
@alexlamsl you are right. Sorry, ignore my comment. 

I went only over the changelog. I think this is important enough to be stated there explicly. Issue here for reference: https://github.com/gruntjs/grunt-contrib-uglify/pull/554
